### ISSUE TITLE
Newest xDSL firmware for w8980?

### ISSUE THREAD

**Issue by Uka-Uka** [xdarklight/lantiq-xdsl-firmware-info#24]
Hi, Sorry for this trivial question. I just want to know what is the newest xDSL firmware available that's supporting VDSL vectoring?

**Comment by xdarklight** [comment]
that is a tough question because it depends on your provider and the driver version

my approach is:

1. pick anything from https://xdarklight.github.io/lantiq-xdsl-firmware-info/
2. try it
3. if you're satisfied with the result: done - otherwise: start at step 1 again

**Comment by Uka-Uka** [comment]
Thanks for your swift reply!

Fine, I'm picking the Fritzbox 7490 firmware, nothing wrong about that, alright? 

Now since I'm using VDSL anyway, should I care about ADSL annex whether it's A or B?

**Comment by xdarklight** [comment]
personally I don't choose the AVM firmwares because they have a special version number and I hear that they are also using a special driver version (this information is obviously nothing official, so you need to decide for yourself what to do with it)

personally I'm using ``29de7210958de4ba57464685f680dd66e6fb5b36`` for a "Deutsche Telekom" VDSL line.

there's no "Annex" concept with VDSL, so the ADSL (which is Annex specific) part of the firmware is irrelevant and you can choose one or the other.

**Comment by Uka-Uka** [comment]
That's great! I'll give DM200 firmware a shot.

If you're okay with that, would you please give a further explanation about AVM firmwares being on a special version? What kind of an impact I'm expecting? Incompatibility and syncing issues?

**Comment by xdarklight** [comment]
I have no further information on the AVM firmware and it's changes. due to lack of time and because there's an alternative (for example the DM200 firmware binary) I am also not planning to research the differences.

**Comment by Uka-Uka** [comment]
I understand, gonna roll the dice with the DM200 firmware. Thanks for your time, brother!

**Comment by xdarklight** [comment]
you're welcome and good luck with finding the "right" firmware for your setup!
